### ISSUE TITLE
Reproducibility of a previously stylized network not given anymore

### ISSUE THREAD

**Issue by benmaier** [benmaier/netwulf#27] opened 2019-05-17 03:52 UTC
The behavior of reproducing a stylized network should be:

1. Open a network visualization
2. stylize network
3. retrieve stylized network and configs
4. bind retrieved positions to network
5. start new visualization with bound positions and config
6. the new visualization should be exactly the same as the old visualization

I've checked out an old version of the javascript base, namely the following commit https://github.com/benmaier/network_styling_with_d3/commit/86762e292344d145b8d8de8211f201604ee968ec

Then I ran the following code 

```python
from netwulf.tools import bind_positions_to_network
import networkx as nx
import pprint
pp = pprint.PrettyPrinter(indent=4)

G = nx.Graph()
G.add_nodes_from(range(10))
G.add_nodes_from("abcde")
G.add_edges_from([("a","b")])

from netwulf import visualize
props, config = visualize(G)
config['Zoom'] = 0.666

pp.pprint(props)
pp.pprint(config)
bind_positions_to_network(G, props)
visualize(G, config=config)
```

this produces the first vis:

<img width="289" alt="Screen Shot 2019-05-17 at 05 48 09" src="https://user-images.githubusercontent.com/10728380/57901959-6d2ad900-7867-11e9-9782-b9327f42467d.png">

and then the second vis:

<img width="281" alt="Screen Shot 2019-05-17 at 05 48 21" src="https://user-images.githubusercontent.com/10728380/57901966-72882380-7867-11e9-9845-adf43a66b95a.png">

Afterwards I've checked out the following commit of the javascript base, which is this: https://github.com/benmaier/network_styling_with_d3/commit/a88f4d37aaffb6c3829fa4bf409b6628976b3d55

Now the first vis is

<img width="289" alt="Screen Shot 2019-05-17 at 05 48 09" src="https://user-images.githubusercontent.com/10728380/57902000-951a3c80-7867-11e9-834d-9024a3c1a0d5.png">

and the second vis is

<img width="568" alt="Screen Shot 2019-05-17 at 05 50 18" src="https://user-images.githubusercontent.com/10728380/57902023-acf1c080-7867-11e9-94f7-ac3840612e62.png">

which is different, but it shouldn't be, right?

I think the part of the code which is responsible for this is the part I commented here:

https://github.com/benmaier/network_styling_with_d3/commit/a88f4d37aaffb6c3829fa4bf409b6628976b3d55#r33573089

**Comment by ulfaslak** [comment] 2019-05-17 07:18
Actually, the problem is in the `else`, where, if nodes have `x` and `y` properties but the graph has no `xlim` and `ylim` properties, node-positions are recomputed such as to use the entire canvas space available. It's nice if someone gives their node position in obscure coordinate ranges (like GPS coordinates, grid positions in nanometers, etc). I think the proper way to fix this is:
    
1. In `bind_positions_to_network`, add `xlim` and `ylim` attributes to the `G.graph` object (`graph` is a dictionary attribute that an `nx.Graph` has dedicated for storing graph attributes) such that, in `netwulf.visualize`, `nx.node_link_data(G)` produces a dictionary that has an entry `'graph': {'xlim': [lowerx, upperx], 'ymin': [lowery, uppery]}`, then
2. In the vis.js every lookup in `graph` or `masterGraph` for `xlim` and `ylim` get changed from `graph['xlim']` to `graph['graph']['xlim'].

I'll try this and report back.

**Comment by benmaier** [comment] 2019-05-17 07:36
Ah, I see! Sounds reasonable. Also, I suggest once this is implemented and tests run smoothly we bump the whole thing up to v0.1

**Comment by ulfaslak** [comment] 2019-05-17 09:04
Changes to `netwulf` (a305733cde3bc93b324a8c9c8451c64e72b64d12):

* **In `tools.py`**: `bind_positions_to_network` -> `bind_properties_to_network`. The updated function defaults to binding all properties to the `nx.Graph` object, but has an argument for untoggling binding for each property. `xlim` and `ylim` are now stored in the `G.graph` dict.
* **In `interactive.py`**: I made a small update so the dictionary resulting from `nx.node_link_data(G)` is flattened, before it is saved. Thus, it ends up almost identical to the `posted_network_properties` that `visualize` returns.

There's still a problem then `config['zoom']` is changed. This needs to be fixed in https://github.com/ulfaslak/network_styling_with_d3.

**Comment by ulfaslak** [comment] 2019-05-17 11:43
Alright, I thought about this a bit now. From a user's perspective it makes sense that setting `config['zoom']` should be equivalent to pulling the slider... But it gets a little complicated due to the way zoom is implemented in the visualization. Nodes have d3 simulation coordinates, but using the `zoomScaler` nodes are rendered elsewhere. For example, a node with coordinates `x, y` is rendered is in `zoomScaler(x), zoomScaler(y)`. So the `zoomScaler` is basically a (two-way) may between simulation coordinates and canvas coordinates (and vice versa). Now, when we return the node coordinates to Python, it is the canvas coordinates we return, simply because it simplifies re-rendering the graph in Matplotlib. This is all fine. The problem, however, is when we overwrite `config['zoom']` the program suddenly no longer knows what the simulation coordinates were. Even worse, as-is it will assume that the simulation coordinates are those obtained with a `zoomScaler` initiated with a different `config['zoom']` value.

So if we e.g. lower `config['zoom']` from 1.5 to 0.66, it's like saying "actually these canvas coordinates are contracted compared to the simulation coordinates". So the simulation coordinates are now different (more spread out), and the rendered network is contracted 0.66 in relation to that. Effectively, the nodes are going to appear to be in the same position on the canvas, only with smaller node sizes.

A way to enable the "user-intuitive" behavior would be to:

1. Return to Python, not the canvas coordinates, but the simulation coordinates
2. Change the `draw_netwulf` function so it also takes the `config` as input and then uses config['zoom'] to put the nodes in the "canvas positions".

**Alternatively**, we return to Python the simulation node-positions in the original 'x' and 'y' keys and then add extra keys called 'x_canvas', and 'y_canvas', that only matplotlib uses.

**Comment by ulfaslak** [comment] 2019-05-17 11:59
Btw, no need to wrap your head around all of that, I mostly wrote it out to understand it myself. I'll go for the **alternative** solution. For reproduction, it's much more elegant that we return the simulation coordinates.

b4bef4ac03a8d24427a75235038ac003b01c69c0

**Closed as completed** 2019-05-17 12:51 UTC
Labels: bug

**Comment by ulfaslak** [comment] 2019-05-17 12:52
Now you can try this:
```Python
from netwulf.tools import bind_properties_to_network
from netwulf import visualize
import networkx as nx

G = nx.Graph()
G.add_nodes_from(range(10))
G.add_nodes_from("abcde")
G.add_edges_from([("a","b")])

props, config = visualize(G)
config['zoom'] = 0.666

bind_properties_to_network(G, props)
visualize(G, config=config)
```

**Comment by benmaier** [comment] 2019-05-23 12:32
works flawlessly now, thanks!

**Comment by benmaier** [comment] 2019-05-23 12:32
even though `config['zoom'] = 0.666` is not necessary anymore now
